### ISSUE TITLE
Add rweekly podcast episode links to weekly releases

### ISSUE THREAD

**Issue by parmsam** [rweekly/rweekly.org#1061]
It would be convenient for readers like myself to have the rweekly podcast episode links (from https://rweekly.fireside.fm/) within the weekly releases along with other content links. Maybe it could have its own section. Sometimes I miss an episode that provides a nice quick summary (with use of 2.0x speed) of interesting content in the week's release.

**Comment by tonyelhabr** [comment]
are you suggesting that we link the previous week's podcast? i suppose that's reasonable. 

as for the podcast for the current week, we would have to do that retroactively, since @rpodcast records it after the newsletter release. i'm not sure it's reasonable to expect the curator for a given week to do this.

**Comment by rpodcast** [comment]
In a perfect situation I would be able to have the recording completed in tandem with the issue release, but that likely won't happen due to a myriad of reasons. But I could simply edit that week's issue post to add a direct link to the episode once the podcast is published. I'll discuss with that idea with the team.

**Comment by parmsam** [comment]
Thank you for considering the idea. Sorry, I didn't initially realize the delay between the release of the week's newsletter and the podcast episode. One benefit may be a boost in listenership.

**Comment by tonyelhabr** [comment]
we'll discuss with the team, as @rpodcast noted
