### ISSUE TITLE
Adding diffify links

### ISSUE THREAD

**Issue by csgillespie** [rweekly/rweekly.org#1092]
Love rweekly BTW!

---

I wonder if you would consider adding links to diffify for updated packages? In the last version of rweekly, I found I was typing in package names to see what had changed, .e.g

 * https://diffify.com/R/opencpu/2.2.7/2.2.8
 * https://diffify.com/R/rtables/0.5.0/0.5.1

Note: massive conflict here, as I'm one of the diffify authors :)

**Comment by BatoolMM** [comment]
`{diffify}` is one of my favourites - We have added it to this week's issue, but since our old infrastructure/tooling are unavailable anymore, it can be a bit more work on the editors in charge of the issue - so can't promise it'll be in each issue but will definitely try!

We hope that's OK with you!

**Comment by csgillespie** [comment]
Thanks @BatoolMM 

>  but since our old infrastructure/tooling are unavailable anymore, it can be a bit more work on the editors in charge of the issue 

Is that something we could contribute/help with?

**Comment by parmsam** [comment]
Hi @csgillespie. We've updated our helper script to generate diffify links for updated CRAN packages by default now. That should make it easy for us to include them in future issues. Thanks for reaching out.
