### ISSUE TITLE
Mention R Weekly podcast in podcast section?

### ISSUE THREAD

**Issue by maelle** [rweekly/rweekly.org#1121]
:smile_cat:

**Comment by jonmcalder** [comment]
Recently we've been retrospectively adding a link (a few days later) to the RWeekly podcast in the highlights section of each episode so that the podcast episode is paired with each issue it references.

Are you suggesting that we should instead or in addition include a general link to the RWeekly podcast in the podcast section when each issue is released?

**Comment by maelle** [comment]
Yes as it might help readers be aware of it?

**Comment by maelle** [comment]
especially those who read R Weekly right away :wink:

**Comment by parmsam** [comment]
Thanks for the suggestion, @maelle. We've added a general link in the podcast section. It will be included in future releases.

**Comment by maelle** [comment]
Thank you @parmsam!
