### ISSUE TITLE
Consider adding r-universe search result links

### ISSUE THREAD

**Issue by parmsam** [rweekly/rweekly.org#1124]
Add links to New Packages or Updates Package sections. Example search URL for DT package: https://r-universe.dev/search/#DT

**Comment by jonocarroll** [comment]
From [this blog](https://ropensci.org/blog/2022/03/23/runiverse-search/):
> The search index matches words against package names, titles, descriptions, authors and vignette titles.

In the example you show, {tidyfst} matches "DT" because it has a vignette with that name.

I'm not entirely sure having that direct link for _every_ package entry in the newsletter is necessary - what is the proposed benefit to the reader? Would a single link to https://r-universe.dev/search/ in the section be sufficient?

**Comment by parmsam** [comment]
That's a good point. I was thinking the user would pick the first search result that matches the package name, but that would require another decision and click. Yes, it would be sufficient to include the single link instead.
