### ISSUE TITLE
Monitor https://blog.r-project.org/ for R Project Updates section

### ISSUE THREAD

**Issue by TimTaylor** [rweekly/rweekly.org#1198]
I've noticed that blogs from https://blog.r-project.org/ are not currently being mentioned under https://rweekly.org/#RProjectUpdates. It would be great to get these highlighted going forward to expose them to a wider audience. They are great for highlighting some of the work that goes in to R itself and making it run across different platforms.

**Comment by jonocarroll** [comment]
Not there in particular, but the RSS feed *is* queried for new posts to be included like any other post. 

https://github.com/rweekly/rweekly.org/blob/63e305531437a94b8f8ef11b62df65618dbde384/rss_feeds.csv#L385

We could certainly look at also adding these to the RProjectUpdates section when they appear, but that's traditionally been for updates rather than blog posts.
