### ISSUE TITLE
Check duplicated items with scripts or travis-ci

### ISSUE THREAD

**Issue by qinwf** [rweekly/rweekly.org#144]

**Comment by jonocarroll** [comment]
Looping back to this - what would be the best way of compiling a summary of all the existing links sorted by issue? Off the top of my head:

* loop over `_posts/*.md` searching for urls (`"http.*"`) or perhaps just items (`"\\+\\W?\\["`)
* scrape the actual deployed site and collect links

The former uses less bandwidth and probably limits to post items (rather than all the supporting links on the actual page).

From there, split item labels and URLs, split domains and relative links, ...

Depending on how long that takes, it may be worth caching the summary, but let's see. With that generated, another tool could cross-check the issue being edited for prior coverage.

I'm happy to have a first pass at this, but if anyone else is keen feel free to join in.

**Comment by qinwf-nuan** [comment]
Yes, the first way will be the easiest. 

And I think about checking the last 20 `.rmd` to save time. If a link is not presented in the last 20 `.rmd` , and it is OK to add it to the draft.

**Comment by qinwf** [comment]
Yes, the first way will be the easiest. 

And I think about checking the last 20 `.rmd` to save time. If a link is not presented in the last 20 `.rmd` , and it is OK to add it to the draft.

**Comment by jonocarroll** [comment]
Good point - I'll have a go at getting that to work. Cheers!

**Comment by qinwf** [comment]
I disabled travis-ci months ago because there are too many warnings.

You are the admin on this repo, please to check whether you can update the setting on travis-ci.org.

If you can not edit the travis-ci setting, please let me know. 

And maybe the checking scripts can be run with the rweekly-highlight app. So, we can run the scripts before generating highlights.

If it runs with highlight-app, there is no need for travis-ci.

**Comment by jonocarroll** [comment]
Perhaps, but I'm happy to just have scripts to run occasionally.

**Comment by qinwf** [comment]
That's great. Thanks.

**Comment by maelle** [comment]
To extract URLs I'd recommend using commonmark cf https://ropensci.org/technotes/2018/09/05/commonmark/ (converting .md to XML or html and extracting the URLs by XPath, rather than regular expressions).

Then we could maybe use GH actions instead of Travis? That'd mean great flexibility in scheduling the frequency of the script execution. https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule the syntax looks complicated but if you edit the workflow file from GitHub there are suggestions.

**Comment by jonocarroll** [comment]
Do we want to have it actually automated or just scripted? It seems like a "while you're editing" event rather than something to flag after pushing.

We could **also** have it run with a GH action, but for starters I'd have a look at running it manually.

**Comment by qinwf** [comment]
We can start with the easy one `running it manually`?

**Comment by maelle** [comment]
Right, correct!

**Comment by maelle** [comment]
I'll work on a script right now.
