### ISSUE TITLE
Update submit page

### ISSUE THREAD

**Issue by qinwf** [rweekly/rweekly.org#226]
related https://twitter.com/StatnMap/status/966953594439241729

**Comment by gadenbuie** [comment]
I also found this confusing. Primarily because the help text under the submit form mentions RSS feeds, which seems to imply that that is the purpose of the submit form. This implication is later re-inforced by the text "You can submit posts by creating pull requests on GitHub." which leads me to think that individual posts have to be submitted via PRs. I have definitely _not posted_ a single link before due to the perceived burden of submitting a PR, but it only occurred to me today that the submit form might accept individual links as well. 🤷‍♂️

**Comment by gadenbuie** [comment]
Maybe just add this line from the README to the submit page?

> **Submit your links or feeds for R Weekly posts and podcasts** via going to rweekly.org/submit.

**Comment by qinwf** [comment]
Thanks. Updated in https://github.com/rweekly/rweekly.org/commit/01e1267cd49b43dbaf952b3292de41ebe7f986d3

**Comment by rstub** [comment]
BTW, is a PR or the submit form preferred for individual posts?

**Comment by maelle** [comment]
@qinwf can we close this?

@rstub a PR in my opinion (let's see if other editors disagree) for 2 reasons:
* you can put the link directly in the section you feel is appropriate.
* if we for instance deem the link is out-of-scope, there's a transparent record of our decision (whereas with a link, we'd just not add it, we have no way to get back to you).

**Comment by jonmcalder** [comment]
Agree with your reasons above @maelle 👍
