### ISSUE TITLE
Screencast for rweekly submission

### ISSUE THREAD

**Issue by sinarueeger** [rweekly/rweekly.org#571]
Hi, 

Following a superb suggestion by @maelle I have created a screencast of showing a rweekly submission via a PR (@leynu tested it in #570). 

You can download it [here](https://drive.switch.ch/index.php/s/GcbrBOWIIFUpU6B).

_Purpose_: A PR is difficult to do if you have never done one before. The screencast shows the few steps and hopefully helps new-to-PR folks. 

I could have added it to the [README.md](https://github.com/rweekly/rweekly.org/blob/gh-pages/README.md) directly, but I think you should first have a look at it and decide whether this is the way you want a PR to be done (please give feedback if not, so I can redo it). 

Should the screencast be uploaded to any video hosting platform?

Sina

**Comment by maelle** [comment]
Again, this is awesome! Thanks a lot Sina!

There's no sound, correct?

I like the approach you show because of the things it teaches (fork, then edit, then view, then make the PR) as opposed to the shortcut I'd have used (clicking on the Edit button of the draft file and letting GitHub do the forking for me), and would love for the video to be in the README! What do others think?

**Comment by sinarueeger** [comment]
Thanks Maëlle!
Correct, no sound. It would probably better with a voice commenting what is done, not very fond of my own voice though ;-)

**Comment by maelle** [comment]
Now linked from the README, I had forgotten to close the issue.
