### ISSUE TITLE
Item under "Updates from R-Core" is nothing to do with R-Core

### ISSUE THREAD

**Issue by barryrowlingson** [rweekly/rweekly.org#588]
The item:

R Project Updates
  Updates from R Core: ( developer.r-project.org ) 
     Data-Driven Tracking and Discovery of R Consortium Activities ( r-consortium.org ) 

is nothing to do with R-Core.

Source is I think here:

https://github.com/rweekly/rweekly.org/blob/92764f1079e27f00afdd68a207ff7cf1f845116d/_posts/2019-11-18-2019-46.md#L157

**Comment by jonocarroll** [comment]
Apologies, this is on me. I overlooked the formatting and didn't see there was a colon there. The R Core entry is there every week and I'm not sure why it has a colon. R Core entry should be an item, and R Consortium entry should be an item. Fixed in 4c71db1cd39427c81c52adbfa46b6217e7604690 and should be pushed out shortly.

Also flagged by @eddelbuettel - thank you both for your feedback.
